---
kind: pipeline
type: kubernetes
name: digitalocean

steps:
- name: preview
  image: pulumi/pulumi:latest
  commands:
    - npm ci
    - pulumi preview --stack digitalocean --non-interactive
  environment:
    PULUMI_ACCESS_TOKEN:
      from_secret: pulumi-token
  when:
    event:
      include:
        - pull_request

---
kind: pipeline
type: kubernetes
name: homelab

steps:
- name: preview
  image: pulumi/pulumi:latest
  commands:
    - npm ci
    - pulumi preview --stack homelab --non-interactive
  environment:
    PULUMI_ACCESS_TOKEN:
      from_secret: pulumi-token
  when:
    event:
      include:
        - pull_request
---
kind: secret
name: pulumi-token
get:
  path: pulumi-token
  name: token
